package org.dyg.sample.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.dyg.sample.model.Sample;
import org.dyg.sample.model.SampleExample;

public interface SampleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_sample
     *
     * @mbggenerated Thu May 07 17:41:40 CST 2015
     */
    int countByExample(SampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_sample
     *
     * @mbggenerated Thu May 07 17:41:40 CST 2015
     */
    int deleteByExample(SampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_sample
     *
     * @mbggenerated Thu May 07 17:41:40 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_sample
     *
     * @mbggenerated Thu May 07 17:41:40 CST 2015
     */
    int insert(Sample record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_sample
     *
     * @mbggenerated Thu May 07 17:41:40 CST 2015
     */
    int insertSelective(Sample record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_sample
     *
     * @mbggenerated Thu May 07 17:41:40 CST 2015
     */
    List<Sample> selectByExample(SampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_sample
     *
     * @mbggenerated Thu May 07 17:41:40 CST 2015
     */
    Sample selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_sample
     *
     * @mbggenerated Thu May 07 17:41:40 CST 2015
     */
    int updateByExampleSelective(@Param("record") Sample record, @Param("example") SampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_sample
     *
     * @mbggenerated Thu May 07 17:41:40 CST 2015
     */
    int updateByExample(@Param("record") Sample record, @Param("example") SampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_sample
     *
     * @mbggenerated Thu May 07 17:41:40 CST 2015
     */
    int updateByPrimaryKeySelective(Sample record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_sample
     *
     * @mbggenerated Thu May 07 17:41:40 CST 2015
     */
    int updateByPrimaryKey(Sample record);
}